### ISSUE TITLE
On debian system, simple_pose.sh and pose_camera.py run failed with RuntimeError error.

### ISSUE THREAD

**Issue by GQ411** [google-coral/project-posenet#81] opened 2022-01-27 05:25 UTC
### Description

our system version was 5.10.64 

```shell
cat /proc/version
Linux version 5.10.64 (builder@f1f16f0420d2) (aarch64-linux-gnu-gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PREEMPT Wed Jan 12 08:21:50 UTC 2022
root@iot2050-debian:~/coral/project-posenet#
```

when executed python3 simple_pose.py, it meet this error. we had reboot it but always meet this error, same error occurred when executed python3 pose_camera.py.

```shell
root@iot2050-debian:~/coral/project-posenet# python3 simple_pose.py
Traceback (most recent call last):
  File "/root/coral/project-posenet/simple_pose.py", line 28, in <module>
    poses, inference_time = engine.DetectPosesInImage(pil_image)
  File "/root/coral/project-posenet/pose_engine.py", line 127, in DetectPosesInImage
    self.run_inference(input_data.flatten())
  File "/root/coral/project-posenet/pose_engine.py", line 102, in run_inference
    edgetpu.run_inference(self._interpreter, input_data)
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 205, in run_inference
    invoke_with_membuffer(interpreter_handle, input_data.ctypes.data,
RuntimeError: InvokeWithMemBuffer failed: Subgraph is already in use. Using an interpreter or a subgraph in multiple threads is not supported. Recursion in the graph is not supported.
root@iot2050-debian:~/coral/project-posenet#
```

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Linux

### Coral Device

Mini PCIe

### Programming Language

Python 3.9

### Relevant Log Output

```shell
cat /proc/version
Linux version 5.10.64 (builder@f1f16f0420d2) (aarch64-linux-gnu-gcc (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP PREEMPT Wed Jan 12 08:21:50 UTC 2022
root@iot2050-debian:~/coral/project-posenet#

when executed python3 simple_pose.py, it meet this error. we had reboot it but always meet this error

root@iot2050-debian:~/coral/project-posenet# python3 simple_pose.py
Traceback (most recent call last):
  File "/root/coral/project-posenet/simple_pose.py", line 28, in <module>
    poses, inference_time = engine.DetectPosesInImage(pil_image)
  File "/root/coral/project-posenet/pose_engine.py", line 127, in DetectPosesInImage
    self.run_inference(input_data.flatten())
  File "/root/coral/project-posenet/pose_engine.py", line 102, in run_inference
    edgetpu.run_inference(self._interpreter, input_data)
  File "/usr/lib/python3/dist-packages/pycoral/utils/edgetpu.py", line 205, in run_inference
    invoke_with_membuffer(interpreter_handle, input_data.ctypes.data,
RuntimeError: InvokeWithMemBuffer failed: Subgraph is already in use. Using an interpreter or a subgraph in multiple threads is not supported. Recursion in the graph is not supported.
root@iot2050-debian:~/coral/project-posenet#
```
</details>

**Comment by hjonnala** [comment] 2022-01-27 14:41
Hi @GQ411 can you please share the following details. Thanks!

```
Python 3.9.7 (default, Sep  3 2021, 06:18:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflite_runtime as tflite
>>> import pycoral
>>> from pycoral.utils.edgetpu import get_runtime_version
>>> get_runtime_version()
'BuildLabel(COMPILER=6.3.0 20170516,DATE=redacted,TIME=redacted), RuntimeVersion(14)'
>>> tflite.__version__
'2.5.0.post1'
>>> pycoral.__version__
'2.0.0'
>>> 
```

**Comment by GQ411** [comment] 2022-01-28 02:49
Hi hjonnala, 

Thanks for your replay, I check them like following:

```
root@iot2050-debian:~# python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflite_runtime as tflite
>>> import pycoral
>>> from pycoral.utils.edgetpu import get_runtime_version
>>> get_runtime_version()
'BuildLabel(COMPILER=10.2.1 20210110,DATE=Dec  9 2021,TIME=20:56:53), RuntimeVersion(14)'
>>> tflite.__version__
'2.5.0'
>>> pycoral.__version__
'2.0.0'
>>>
```

**Comment by hjonnala** [comment] 2022-01-28 16:12
Hi, the error is due to tflite runtime version. 

Please uninstall pycoral and tflite runtime and install it using again with [sudo apt-get install python3-pycoral](https://coral.ai/software/#debian-packages)..

**Comment by jan-kiszka** [comment] 2022-01-30 07:51
Seems like it is resolved in latest [meta-coral](https://github.com/siemens/meta-coral) by moving to tflite 2.5.2.

@hjonnala We cannot use your pre-compiled binaries because we want to redistribute them, and that implies reproducibility without binary dependencies. Also, we'd like to get all this properly packaged by Debian one day so that most user do not need to fall back to an extra repo any more to get started. meta-coral is a stepping stone for that vision.

**Comment by hjonnala** [comment] 2022-02-07 18:14
Hi @jan-kiszka pleae check this page to build Coral libraries for your application: https://coral.ai/docs/notes/build-coral/

Thanks!

**Closed as completed by hjonnala** 2022-02-07 18:14 UTC
Labels: type:support, subtype:ubuntu/linux, Hardware:Mini PCIe
